"""
Generate per-instrument HTML datasheets from InstrumentRow objects.
Produces one HTML file per instrument, bundled into a ZIP archive.

Schema follows the deliverable in `ref/05011-CPP-01-00-4V-IIN-01-K-101-0001_M.pdf`.
"""
import zipfile
from pathlib import Path
from typing import List


_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; font-family: Arial, sans-serif; font-size: 11px; }
body { padding: 16px; background: #fff; }
h2 { font-size: 14px; font-weight: bold; margin-bottom: 12px; color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 6px; }
h3 { font-size: 11px; font-weight: bold; background: #1a1a2e; color: #fff; padding: 4px 8px; margin: 12px 0 0 0; }
table { width: 100%; border-collapse: collapse; }
td { border: 1px solid #ccc; padding: 4px 8px; vertical-align: top; }
td.label { width: 35%; background: #f0f4f8; font-weight: bold; color: #333; }
td.value { color: #111; }
td.value.tbd { color: #c0392b; font-style: italic; }
.header-table { width: 100%; border: 2px solid #1a1a2e; margin-bottom: 4px; }
.header-table td { border: 1px solid #999; padding: 6px 10px; }
.footer { margin-top: 16px; font-size: 9px; color: #aaa; text-align: right; }
"""


def _val(v: str, empty_label: str = "—") -> tuple:
    if not v or v == "—":
        return empty_label, "tbd"
    if v == "TBD":
        return "TBD", "tbd"
    return v, "value"


def _row(label: str, value: str) -> str:
    display, cls = _val(value)
    return f'<tr><td class="label">{label}</td><td class="value {cls}">{display}</td></tr>'


def generate_datasheet_html(inst) -> str:
    """Generate a single instrument datasheet as an HTML string."""
    tag = inst.tag_number or "UNKNOWN"
    inst_type = inst.instrument_type_description or "—"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Instrument Datasheet — {tag}</title>
<style>{_CSS}</style>
</head>
<body>

<h2>Instrument Datasheet</h2>

<table class="header-table">
  <tr>
    <td class="label">Tag Number</td>
    <td class="value" style="font-weight:bold;font-size:13px;">{tag}</td>
    <td class="label">Instrument Type</td>
    <td class="value">{inst_type}</td>
  </tr>
  <tr>
    <td class="label">Tag Service</td>
    <td class="value" colspan="3">{_val(inst.tag_service)[0]}</td>
  </tr>
  <tr>
    <td class="label">P&amp;ID</td>
    <td class="value">{inst.pid_no or "—"}</td>
    <td class="label">Status</td>
    <td class="value">{_val(inst.status)[0]}</td>
  </tr>
</table>

<h3>Process Connection</h3>
<table>
  {_row("Line Number", inst.line_number)}
  {_row("Equipment No", inst.equipment_no)}
  {_row("Location", inst.location)}
  {_row("VLV Fail", inst.vlv_fail)}
</table>

<h3>Electrical / Signal</h3>
<table>
  {_row("Power Supply", inst.power_supply)}
  {_row("Signal Voltage Level", inst.signal_voltage_level)}
</table>

<h3>Hazardous Area</h3>
<table>
  {_row("Vendor Scope", inst.vendor_scope)}
  {_row("Hazardous Area Classification", inst.hazardous_area_classification)}
  {_row("Electrical Area Certification", inst.electrical_area_certification)}
</table>

<h3>Range</h3>
<table>
  {_row("Range Min", inst.range_min)}
  {_row("Range Max", inst.range_max)}
  {_row("Range UoM", inst.range_uom)}
</table>

<h3>Vendor Information</h3>
<table>
  {_row("Data Sheet / Requisition №", inst.data_sheet_requisition_no)}
  {_row("Manufacturer", inst.manufacturer)}
  {_row("Model", inst.model)}
</table>

<h3>Remarks</h3>
<table>
  {_row("Remarks", inst.remarks or "—")}
</table>

<div class="footer">Generated by Qong P&amp;ID Extractor &nbsp;|&nbsp; Fields marked TBD require engineering input</div>

</body>
</html>"""
    return html


def write_datasheet_zip(inst_rows: List, zip_path: str) -> int:
    """Write one HTML datasheet per instrument into a ZIP archive."""
    if not inst_rows:
        return 0

    Path(zip_path).parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for inst in inst_rows:
            tag = (inst.tag_number or "UNKNOWN").replace("/", "-").replace("\\", "-")
            filename = f"{tag}.html"
            html = generate_datasheet_html(inst)
            zf.writestr(filename, html)

    return len(inst_rows)
