"""
Generate per-instrument HTML datasheets from InstrumentRow objects.
Produces one HTML file per instrument, bundled into a ZIP archive.
"""
import zipfile
from pathlib import Path
from typing import List


_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; font-family: Arial, sans-serif; font-size: 11px; }
body { padding: 16px; background: #fff; }
h2 { font-size: 14px; font-weight: bold; margin-bottom: 12px; color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 6px; }
h3 { font-size: 11px; font-weight: bold; background: #1a1a2e; color: #fff; padding: 4px 8px; margin: 12px 0 0 0; }
table { width: 100%; border-collapse: collapse; }
td { border: 1px solid #ccc; padding: 4px 8px; vertical-align: top; }
td.label { width: 35%; background: #f0f4f8; font-weight: bold; color: #333; }
td.value { color: #111; }
td.value.tbd { color: #999; font-style: italic; }
td.value.later { color: #c0392b; font-style: italic; }
.header-table { width: 100%; border: 2px solid #1a1a2e; margin-bottom: 4px; }
.header-table td { border: 1px solid #999; padding: 6px 10px; }
.footer { margin-top: 16px; font-size: 9px; color: #aaa; text-align: right; }
"""


def _val(v: str, empty_label: str = "—") -> tuple:
    """Return (display_value, css_class)."""
    if not v or v == "—":
        return empty_label, "tbd"
    if v in ("TBD",):
        return "TBD", "tbd"
    if v in ("LATER",):
        return "LATER", "later"
    return v, "value"


def _row(label: str, value: str) -> str:
    display, cls = _val(value)
    return f'<tr><td class="label">{label}</td><td class="value {cls}">{display}</td></tr>'


def generate_datasheet_html(inst) -> str:
    """Generate a single instrument datasheet as an HTML string."""
    tag = inst.tag_number or "UNKNOWN"
    inst_type = inst.instrument_type or inst.tag_number

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Instrument Datasheet — {tag}</title>
<style>{_CSS}</style>
</head>
<body>

<h2>Instrument Datasheet</h2>

<table class="header-table">
  <tr>
    <td class="label">Tag Number</td>
    <td class="value" style="font-weight:bold;font-size:13px;">{tag}</td>
    <td class="label">Instrument Type</td>
    <td class="value">{inst_type}</td>
  </tr>
  <tr>
    <td class="label">P&amp;ID No</td>
    <td class="value">{inst.pid_no or "—"}</td>
    <td class="label">Rev No</td>
    <td class="value">{inst.rev_no or "—"}</td>
  </tr>
</table>

<h3>Identification</h3>
<table>
  {_row("Unit Number", inst.unit_number)}
  {_row("Loop Name", inst.loop_name)}
  {_row("Service Description", inst.service_description)}
  {_row("Location", inst.location)}
  {_row("System (DCS/ESD/UCP)", inst.system)}
  {_row("Technical Room", inst.technical_room)}
</table>

<h3>Process Connection</h3>
<table>
  {_row("Line No", inst.line_no)}
  {_row("Equipment No", inst.equipment_no)}
</table>

<h3>Electrical / Signal</h3>
<table>
  {_row("IO Type", inst.io_type)}
  {_row("Signal Type", inst.signal_type)}
  {_row("Signal Level", inst.signal_level)}
  {_row("IO Grouping", inst.io_grouping)}
  {_row("External Power Supply", inst.external_power_supply)}
</table>

<h3>Analog Ranges</h3>
<table>
  {_row("Range Low", inst.analog_range_low)}
  {_row("Range High", inst.analog_range_high)}
  {_row("Engineering Unit", inst.analog_range_eu)}
</table>

<h3>Alarm Setpoints</h3>
<table>
  {_row("HH Alarm Limit", inst.hh_alarm_limit)}
  {_row("H Alarm Limit", inst.h_alarm_limit)}
  {_row("L Alarm Limit", inst.l_alarm_limit)}
  {_row("LL Alarm Limit", inst.ll_alarm_limit)}
</table>

<h3>Wiring / Installation</h3>
<table>
  {_row("Junction Box / Panel", inst.junction_box)}
  {_row("Multi-Cable Pair No", inst.multi_cable_pair_no)}
  {_row("Hook-up Drawing", inst.hookup_drawing)}
</table>

<h3>Vendor Information</h3>
<table>
  {_row("Manufacturer", inst.manufacturer)}
  {_row("Model No", inst.model_no)}
  {_row("Inst. Datasheet Ref", inst.inst_datasheet)}
</table>

<h3>Remarks</h3>
<table>
  {_row("Remark", inst.remark or "—")}
</table>

<div class="footer">Generated by Qong P&amp;ID Extractor &nbsp;|&nbsp; Fields marked TBD require engineering input &nbsp;|&nbsp; Fields marked LATER require vendor data</div>

</body>
</html>"""
    return html


def write_datasheet_zip(inst_rows: List, zip_path: str) -> int:
    """
    Write one HTML datasheet per instrument into a ZIP archive.
    Returns count of datasheets written.
    """
    if not inst_rows:
        return 0

    Path(zip_path).parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for inst in inst_rows:
            tag = (inst.tag_number or "UNKNOWN").replace("/", "-").replace("\\", "-")
            filename = f"{tag}.html"
            html = generate_datasheet_html(inst)
            zf.writestr(filename, html)

    return len(inst_rows)
