// GENERATED — do not edit; run scripts/gen_taxonomy_ts.py
//
// Source: webapp/taxonomy.json. COLOR/GLYPH keys are
// `${entity_class}|${sub_class}`; DISPLAY_NAME is keyed by sub_class.

export const SCHEMA_VERSION = 1;

export const COLOR_BY_KEY: Record<string, string> = {
  "valve|BV": "#86D8C4",
  "valve|NCBV": "#86A8E8",
  "valve|GT": "#7EC9C2",
  "valve|BF": "#FF6B6B",
  "valve|CK": "#D8C794",
  "valve|DB": "#7FD4D2",
  "valve|RELIEF_SAFETY": "#A8DD92",
  "valve|GL": "#A8DD92",
  "valve|3WAY_RELIEF": "#C49AE2",
  "valve|CV": "#C49AE2",
  "valve|VB": "#8EE0CE",
  "valve|VF": "#92B4E8",
  "valve|VD": "#EBA6C6",
  "valve|PV": "#EB8070",
  "valve|SB": "#C3B4EC",
  "instrument|FT": "#E5CBA0",
  "instrument|PT": "#C5BCEC",
  "instrument|TT": "#8585D6",
  "instrument|LT": "#B4ACE6",
  "instrument|AT": "#EC9696",
  "instrument|PIC": "#C6C6CE",
  "instrument|FIC": "#ACDC90",
  "instrument|TIC": "#ECA666",
  "instrument|LIC": "#EC8698",
  "equipment|Pump": "#8CCC76",
  "equipment|Vessel": "#B496DC",
  "equipment|Exchanger": "#DCD486",
  "equipment|Tank": "#DCC68C",
  "valve|PNEUCTRL": "#EB8070",
};

export const GLYPH_KIND_BY_KEY: Record<string, string> = {
  "valve|BV": "valve_bv",
  "valve|NCBV": "valve_ncbv",
  "valve|GT": "valve_gt",
  "valve|BF": "valve_bf",
  "valve|CK": "valve_ck",
  "valve|DB": "valve_db",
  "valve|RELIEF_SAFETY": "valve_gen",
  "valve|GL": "valve_gl",
  "valve|3WAY_RELIEF": "valve_gen",
  "valve|CV": "valve_cv",
  "valve|VB": "valve_gen",
  "valve|VF": "valve_gen",
  "valve|VD": "valve_gen",
  "valve|PV": "valve_pneuctrl",
  "valve|SB": "valve_gen",
  "instrument|FT": "inst_field",
  "instrument|PT": "inst_field",
  "instrument|TT": "inst_field",
  "instrument|LT": "inst_field",
  "instrument|AT": "inst_field",
  "instrument|PIC": "inst_field",
  "instrument|FIC": "inst_field",
  "instrument|TIC": "inst_field",
  "instrument|LIC": "inst_field",
  "equipment|Pump": "pump",
  "equipment|Vessel": "inst_field",
  "equipment|Exchanger": "inst_field",
  "equipment|Tank": "inst_field",
  "valve|PNEUCTRL": "valve_pneuctrl",
};

export const DISPLAY_NAME_BY_SUB: Record<string, string> = {
  "BV": "Ball Valve",
  "NCBV": "NC Ball Valve",
  "GT": "Gate Valve",
  "BF": "Butterfly Valve",
  "CK": "Check Valve",
  "DB": "Double Block",
  "RELIEF_SAFETY": "Relief / Safety Valve",
  "GL": "Globe Valve",
  "3WAY_RELIEF": "3-Way Relief Valve",
  "CV": "Control Valve",
  "VB": "Block Valve",
  "VF": "Flow Valve",
  "VD": "Drain Valve",
  "PV": "Pressure Valve",
  "SB": "Sample/Bleed Valve",
  "FT": "Flow Tx",
  "PT": "Pressure Tx",
  "TT": "Temperature Tx",
  "LT": "Level Tx",
  "AT": "Analytic Tx",
  "PIC": "Pressure Ctrl",
  "FIC": "Flow Ctrl",
  "TIC": "Temperature Ctrl",
  "LIC": "Level Ctrl",
  "Pump": "Pump",
  "Vessel": "Vessel",
  "Exchanger": "Exchanger",
  "Tank": "Tank",
  "PNEUCTRL": "Pneumatic Valve",
};

export const PALETTE_DATA: Record<string, { sub: string; color: string }[]> = {
  "valve": [
    { sub: "BV", color: "#86D8C4" },
    { sub: "NCBV", color: "#86A8E8" },
    { sub: "GT", color: "#7EC9C2" },
    { sub: "BF", color: "#FF6B6B" },
    { sub: "CK", color: "#D8C794" },
    { sub: "DB", color: "#7FD4D2" },
    { sub: "RELIEF_SAFETY", color: "#A8DD92" },
    { sub: "GL", color: "#A8DD92" },
    { sub: "3WAY_RELIEF", color: "#C49AE2" },
    { sub: "CV", color: "#C49AE2" },
    { sub: "VB", color: "#8EE0CE" },
    { sub: "VF", color: "#92B4E8" },
    { sub: "VD", color: "#EBA6C6" },
    { sub: "PV", color: "#EB8070" },
    { sub: "SB", color: "#C3B4EC" },
    { sub: "PNEUCTRL", color: "#EB8070" },
  ],
  "instrument": [
    { sub: "FT", color: "#E5CBA0" },
    { sub: "PT", color: "#C5BCEC" },
    { sub: "TT", color: "#8585D6" },
    { sub: "LT", color: "#B4ACE6" },
    { sub: "AT", color: "#EC9696" },
    { sub: "PIC", color: "#C6C6CE" },
    { sub: "FIC", color: "#ACDC90" },
    { sub: "TIC", color: "#ECA666" },
    { sub: "LIC", color: "#EC8698" },
  ],
  "equipment": [
    { sub: "Pump", color: "#8CCC76" },
    { sub: "Vessel", color: "#B496DC" },
    { sub: "Exchanger", color: "#DCD486" },
    { sub: "Tank", color: "#DCC68C" },
  ],
};

export const CLASS_NAMES: string[] = ["valve_bv", "valve_ncbv", "valve_gt", "valve_bf", "valve_ck", "valve_db", "valve_relief_safety", "valve_gl", "valve_3way_relief", "inst_field", "inst_bpcs", "Motor", "Pump/Dwg Pump", "inst_sis", "SIS-R", "interlock", "inst_local_panel", "arrow_up", "arrow_left", "arrow_right", "arrow_down", "connector_out", "connector_in"];
